### ISSUE TITLE
Remove lodash dependency?

### ISSUE THREAD

**Issue by rodrigograca31** [kelvinhokk/cordova-plugin-localization-strings#56]
I dont understand why we are using loadash for such basic stuff like a forEach....

Also lines like this:

https://github.com/kelvinhokk/cordova-plugin-localization-strings/blob/7314bf4c4ab96d7829c6d9e25d7dc4ae71e893fc/scripts/create_android_strings.js#L23

can be done like this:
```javascript
if (langJson.locale !== undefined && langJson.locale.android !== undefined)
```
right?

**Comment by pklaes** [comment]
Beware, `_.has(langJson, "locale")` returns false if `langJson` is null, whereas `langJson.locale` throws a type error. So although  I'm all for vanilla JS and against dependency creep, I would probably not refactor and just live with it. 

If I were to rewrite, I would use simply

    if (langJson && langJson.locale && langJson.locale.android)

since this is most javascriptish and a value of "" or 0 for any of these wouldn't help us either.

**Comment by rodrigograca31** [comment]
I agree but I hate dependencies and nowadays we depend on stuff for no reason, this is perfect example. 
But yeah I may just live with it because I got better stuff to do then removing 1 dependency in this project
