### ISSUE TITLE
How to set fallback language

### ISSUE THREAD

**Issue by ferreria23** [kelvinhokk/cordova-plugin-localization-strings#59]
When the specific language file is not found, how I can configure the plugin to use a default language?

**Comment by bbialas** [comment]
+1

**Comment by felicienfrancois** [comment]
Have you tried defaultlocale cordova setting ?
https://cordova.apache.org/docs/en/10.x/config_ref/#widget

**Comment by ath0mas** [comment]
**For iOS,**
like @felicienfrancois said, setting `defaultlocale` attribute on your [`<widget>`](https://cordova.apache.org/docs/en/10.x/config_ref/#widget) in _config.xml_ should be fine.
Cordova-IOS will override its [`CFBundleDevelopmentRegion`](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledevelopmentregion), defined to [`en_US`](https://github.com/apache/cordova-ios/blob/master/templates/project/__PROJECT_NAME__/__PROJECT_NAME__-Info.plist#L6) in the template, with your own value.
Given this plugin adds all localization files to the xcode project, each in its own `<lang>` resource folder ; nothing special for the "default" one here as it is the common xcode project structure.

**For Android,**
no such configuration, but, like what this plugin does, the localization files are added with a `-<lang>` suffix and **the "default" one does not have any suffix**.
So I am planning to push a PR soon for this plugin to read the `defaultlocale` from _config.xml_ and apply its value if defined instead of the [currently hardcoded `"en"`](https://github.com/kelvinhokk/cordova-plugin-localization-strings/blob/master/scripts/create_android_strings.js#L167).

> possibly after #64 is merged but inside 4.0.0 too? ping @rodrigograca31
